UPDATE calc_question SET raw_content = CASE id
  WHEN 111 THEN '{"type": "multiplication", "lines": [[{"text": "   26", "type": "text"}], [{"text": "×  21", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   26", "type": "text"}], [{"text": "  52", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "546"}]]}'::jsonb
  WHEN 112 THEN '{"type": "multiplication", "lines": [[{"text": "   16", "type": "text"}], [{"text": "×  59", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "  144", "type": "text"}], [{"text": "  80", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "944"}]]}'::jsonb
  WHEN 113 THEN '{"type": "multiplication", "lines": [[{"text": "    86", "type": "text"}], [{"text": "×   82", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   172", "type": "text"}], [{"text": "  688", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "7052"}]]}'::jsonb
  WHEN 114 THEN '{"type": "multiplication", "lines": [[{"text": "    30", "type": "text"}], [{"text": "×   67", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   210", "type": "text"}], [{"text": "  180", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2010"}]]}'::jsonb
  WHEN 115 THEN '{"type": "multiplication", "lines": [[{"text": "   28", "type": "text"}], [{"text": "×  17", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "  196", "type": "text"}], [{"text": "  28", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "476"}]]}'::jsonb
  WHEN 116 THEN '{"type": "multiplication", "lines": [[{"text": "    51", "type": "text"}], [{"text": "×   58", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   408", "type": "text"}], [{"text": "  255", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2958"}]]}'::jsonb
  WHEN 117 THEN '{"type": "multiplication", "lines": [[{"text": "   17", "type": "text"}], [{"text": "×  57", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "  119", "type": "text"}], [{"text": "  85", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "969"}]]}'::jsonb
  WHEN 118 THEN '{"type": "multiplication", "lines": [[{"text": "    38", "type": "text"}], [{"text": "×   99", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   342", "type": "text"}], [{"text": "  342", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3762"}]]}'::jsonb
  WHEN 119 THEN '{"type": "multiplication", "lines": [[{"text": "    43", "type": "text"}], [{"text": "×   97", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   301", "type": "text"}], [{"text": "  387", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "4171"}]]}'::jsonb
  WHEN 120 THEN '{"type": "multiplication", "lines": [[{"text": "    25", "type": "text"}], [{"text": "×   57", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   175", "type": "text"}], [{"text": "  125", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1425"}]]}'::jsonb
  WHEN 121 THEN '{"type": "multiplication", "lines": [[{"text": "    83", "type": "text"}], [{"text": "×   64", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   332", "type": "text"}], [{"text": "  498", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5312"}]]}'::jsonb
  WHEN 122 THEN '{"type": "multiplication", "lines": [[{"text": "    34", "type": "text"}], [{"text": "×   64", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   136", "type": "text"}], [{"text": "  204", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2176"}]]}'::jsonb
  WHEN 123 THEN '{"type": "multiplication", "lines": [[{"text": "   15", "type": "text"}], [{"text": "×  34", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   60", "type": "text"}], [{"text": "  45", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "510"}]]}'::jsonb
  WHEN 124 THEN '{"type": "multiplication", "lines": [[{"text": "    54", "type": "text"}], [{"text": "×   64", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   216", "type": "text"}], [{"text": "  324", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3456"}]]}'::jsonb
  WHEN 125 THEN '{"type": "multiplication", "lines": [[{"text": "    97", "type": "text"}], [{"text": "×   43", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   291", "type": "text"}], [{"text": "  388", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "4171"}]]}'::jsonb
  WHEN 126 THEN '{"type": "multiplication", "lines": [[{"text": "    46", "type": "text"}], [{"text": "×   32", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    92", "type": "text"}], [{"text": "  138", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1472"}]]}'::jsonb
  WHEN 127 THEN '{"type": "multiplication", "lines": [[{"text": "    25", "type": "text"}], [{"text": "×   60", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "     0", "type": "text"}], [{"text": "  150", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1500"}]]}'::jsonb
  WHEN 128 THEN '{"type": "multiplication", "lines": [[{"text": "    16", "type": "text"}], [{"text": "×   72", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    32", "type": "text"}], [{"text": "  112", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1152"}]]}'::jsonb
  WHEN 129 THEN '{"type": "multiplication", "lines": [[{"text": "    40", "type": "text"}], [{"text": "×   37", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   280", "type": "text"}], [{"text": "  120", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1480"}]]}'::jsonb
  WHEN 130 THEN '{"type": "multiplication", "lines": [[{"text": "    70", "type": "text"}], [{"text": "×   56", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   420", "type": "text"}], [{"text": "  350", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3920"}]]}'::jsonb
END WHERE id IN (111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130);