UPDATE calc_question SET raw_content = CASE id
  WHEN 191 THEN '{"type": "multiplication", "lines": [[{"text": "    908", "type": "text"}], [{"text": "×    64", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3632", "type": "text"}], [{"text": "  5448", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "58112"}]]}'::jsonb
  WHEN 192 THEN '{"type": "multiplication", "lines": [[{"text": "   104", "type": "text"}], [{"text": "×   64", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   416", "type": "text"}], [{"text": "  624", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "6656"}]]}'::jsonb
  WHEN 193 THEN '{"type": "multiplication", "lines": [[{"text": "    701", "type": "text"}], [{"text": "×    84", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2804", "type": "text"}], [{"text": "  5608", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "58884"}]]}'::jsonb
  WHEN 194 THEN '{"type": "multiplication", "lines": [[{"text": "   708", "type": "text"}], [{"text": "×   11", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   708", "type": "text"}], [{"text": "  708", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "7788"}]]}'::jsonb
  WHEN 195 THEN '{"type": "multiplication", "lines": [[{"text": "    605", "type": "text"}], [{"text": "×    60", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  3630", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "36300"}]]}'::jsonb
  WHEN 196 THEN '{"type": "multiplication", "lines": [[{"text": "    709", "type": "text"}], [{"text": "×    80", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  5672", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "56720"}]]}'::jsonb
  WHEN 197 THEN '{"type": "multiplication", "lines": [[{"text": "    408", "type": "text"}], [{"text": "×    39", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3672", "type": "text"}], [{"text": "  1224", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "15912"}]]}'::jsonb
  WHEN 198 THEN '{"type": "multiplication", "lines": [[{"text": "    507", "type": "text"}], [{"text": "×    73", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1521", "type": "text"}], [{"text": "  3549", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "37011"}]]}'::jsonb
  WHEN 199 THEN '{"type": "multiplication", "lines": [[{"text": "   107", "type": "text"}], [{"text": "×   54", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   428", "type": "text"}], [{"text": "  535", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5778"}]]}'::jsonb
  WHEN 200 THEN '{"type": "multiplication", "lines": [[{"text": "    703", "type": "text"}], [{"text": "×    70", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  4921", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "49210"}]]}'::jsonb
  WHEN 201 THEN '{"type": "multiplication", "lines": [[{"text": "    180", "type": "text"}], [{"text": "×    90", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  1620", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "16200"}]]}'::jsonb
  WHEN 202 THEN '{"type": "multiplication", "lines": [[{"text": "   450", "type": "text"}], [{"text": "×   14", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "  1800", "type": "text"}], [{"text": "  450", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "6300"}]]}'::jsonb
  WHEN 203 THEN '{"type": "multiplication", "lines": [[{"text": "    350", "type": "text"}], [{"text": "×    86", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2100", "type": "text"}], [{"text": "  2800", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "30100"}]]}'::jsonb
  WHEN 204 THEN '{"type": "multiplication", "lines": [[{"text": "    500", "type": "text"}], [{"text": "×    95", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2500", "type": "text"}], [{"text": "  4500", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "47500"}]]}'::jsonb
  WHEN 205 THEN '{"type": "multiplication", "lines": [[{"text": "   120", "type": "text"}], [{"text": "×   21", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   120", "type": "text"}], [{"text": "  240", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2520"}]]}'::jsonb
  WHEN 206 THEN '{"type": "multiplication", "lines": [[{"text": "    520", "type": "text"}], [{"text": "×    65", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2600", "type": "text"}], [{"text": "  3120", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "33800"}]]}'::jsonb
  WHEN 207 THEN '{"type": "multiplication", "lines": [[{"text": "    180", "type": "text"}], [{"text": "×    70", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  1260", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "12600"}]]}'::jsonb
  WHEN 208 THEN '{"type": "multiplication", "lines": [[{"text": "   180", "type": "text"}], [{"text": "×   17", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "  1260", "type": "text"}], [{"text": "  180", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3060"}]]}'::jsonb
  WHEN 209 THEN '{"type": "multiplication", "lines": [[{"text": "    260", "type": "text"}], [{"text": "×    59", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2340", "type": "text"}], [{"text": "  1300", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "15340"}]]}'::jsonb
  WHEN 210 THEN '{"type": "multiplication", "lines": [[{"text": "    300", "type": "text"}], [{"text": "×    38", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2400", "type": "text"}], [{"text": "   900", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "11400"}]]}'::jsonb
END WHERE id IN (191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210);