UPDATE calc_question SET raw_content = CASE id
  WHEN 91 THEN '{"type": "multiplication", "lines": [[{"text": "   11", "type": "text"}], [{"text": "×  33", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   33", "type": "text"}], [{"text": "  33", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "363"}]]}'::jsonb
  WHEN 92 THEN '{"type": "multiplication", "lines": [[{"text": "   23", "type": "text"}], [{"text": "×  23", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   69", "type": "text"}], [{"text": "  46", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "529"}]]}'::jsonb
  WHEN 93 THEN '{"type": "multiplication", "lines": [[{"text": "    24", "type": "text"}], [{"text": "×   44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    96", "type": "text"}], [{"text": "   96", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1056"}]]}'::jsonb
  WHEN 94 THEN '{"type": "multiplication", "lines": [[{"text": "   12", "type": "text"}], [{"text": "×  33", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   36", "type": "text"}], [{"text": "  36", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "396"}]]}'::jsonb
  WHEN 95 THEN '{"type": "multiplication", "lines": [[{"text": "   13", "type": "text"}], [{"text": "×  13", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   39", "type": "text"}], [{"text": "  13", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "169"}]]}'::jsonb
  WHEN 96 THEN '{"type": "multiplication", "lines": [[{"text": "   23", "type": "text"}], [{"text": "×  22", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   46", "type": "text"}], [{"text": "  46", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "506"}]]}'::jsonb
  WHEN 97 THEN '{"type": "multiplication", "lines": [[{"text": "    32", "type": "text"}], [{"text": "×   33", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    96", "type": "text"}], [{"text": "   96", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1056"}]]}'::jsonb
  WHEN 98 THEN '{"type": "multiplication", "lines": [[{"text": "   13", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   13", "type": "text"}], [{"text": "  13", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "143"}]]}'::jsonb
  WHEN 99 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  23", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   66", "type": "text"}], [{"text": "  44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "506"}]]}'::jsonb
  WHEN 100 THEN '{"type": "multiplication", "lines": [[{"text": "   23", "type": "text"}], [{"text": "×  23", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   69", "type": "text"}], [{"text": "  46", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "529"}]]}'::jsonb
  WHEN 101 THEN '{"type": "multiplication", "lines": [[{"text": "    76", "type": "text"}], [{"text": "×   74", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   304", "type": "text"}], [{"text": "  532", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5624"}]]}'::jsonb
  WHEN 102 THEN '{"type": "multiplication", "lines": [[{"text": "   44", "type": "text"}], [{"text": "×  18", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "  352", "type": "text"}], [{"text": "  44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "792"}]]}'::jsonb
  WHEN 103 THEN '{"type": "multiplication", "lines": [[{"text": "    23", "type": "text"}], [{"text": "×   93", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    69", "type": "text"}], [{"text": "  207", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2139"}]]}'::jsonb
  WHEN 104 THEN '{"type": "multiplication", "lines": [[{"text": "    66", "type": "text"}], [{"text": "×   47", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   462", "type": "text"}], [{"text": "  264", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3102"}]]}'::jsonb
  WHEN 105 THEN '{"type": "multiplication", "lines": [[{"text": "   17", "type": "text"}], [{"text": "×  12", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   34", "type": "text"}], [{"text": "  17", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "204"}]]}'::jsonb
  WHEN 106 THEN '{"type": "multiplication", "lines": [[{"text": "    54", "type": "text"}], [{"text": "×   28", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   432", "type": "text"}], [{"text": "  108", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1512"}]]}'::jsonb
  WHEN 107 THEN '{"type": "multiplication", "lines": [[{"text": "    93", "type": "text"}], [{"text": "×   45", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   465", "type": "text"}], [{"text": "  372", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "4185"}]]}'::jsonb
  WHEN 108 THEN '{"type": "multiplication", "lines": [[{"text": "    32", "type": "text"}], [{"text": "×   68", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   256", "type": "text"}], [{"text": "  192", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2176"}]]}'::jsonb
  WHEN 109 THEN '{"type": "multiplication", "lines": [[{"text": "    82", "type": "text"}], [{"text": "×   66", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   492", "type": "text"}], [{"text": "  492", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5412"}]]}'::jsonb
  WHEN 110 THEN '{"type": "multiplication", "lines": [[{"text": "    83", "type": "text"}], [{"text": "×   13", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   249", "type": "text"}], [{"text": "   83", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1079"}]]}'::jsonb
END WHERE id IN (91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110);