UPDATE calc_question SET raw_content = CASE id
  WHEN 51 THEN '{"type": "multiplication", "lines": [[{"text": "    44", "type": "text"}], [{"text": "×   41", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    44", "type": "text"}], [{"text": "  176", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1804"}]]}'::jsonb
  WHEN 52 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  33", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   66", "type": "text"}], [{"text": "  66", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "726"}]]}'::jsonb
  WHEN 53 THEN '{"type": "multiplication", "lines": [[{"text": "   33", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   33", "type": "text"}], [{"text": "  33", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "363"}]]}'::jsonb
  WHEN 54 THEN '{"type": "multiplication", "lines": [[{"text": "   31", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   31", "type": "text"}], [{"text": "  31", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "341"}]]}'::jsonb
  WHEN 55 THEN '{"type": "multiplication", "lines": [[{"text": "    41", "type": "text"}], [{"text": "×   42", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    82", "type": "text"}], [{"text": "  164", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1722"}]]}'::jsonb
  WHEN 56 THEN '{"type": "multiplication", "lines": [[{"text": "   13", "type": "text"}], [{"text": "×  33", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   39", "type": "text"}], [{"text": "  39", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "429"}]]}'::jsonb
  WHEN 57 THEN '{"type": "multiplication", "lines": [[{"text": "   31", "type": "text"}], [{"text": "×  13", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   93", "type": "text"}], [{"text": "  31", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "403"}]]}'::jsonb
  WHEN 58 THEN '{"type": "multiplication", "lines": [[{"text": "    41", "type": "text"}], [{"text": "×   44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   164", "type": "text"}], [{"text": "  164", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1804"}]]}'::jsonb
  WHEN 59 THEN '{"type": "multiplication", "lines": [[{"text": "   21", "type": "text"}], [{"text": "×  44", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   84", "type": "text"}], [{"text": "  84", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "924"}]]}'::jsonb
  WHEN 60 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  32", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   44", "type": "text"}], [{"text": "  66", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "704"}]]}'::jsonb
  WHEN 61 THEN '{"type": "multiplication", "lines": [[{"text": "   21", "type": "text"}], [{"text": "×  44", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   84", "type": "text"}], [{"text": "  84", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "924"}]]}'::jsonb
  WHEN 62 THEN '{"type": "multiplication", "lines": [[{"text": "   32", "type": "text"}], [{"text": "×  21", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   32", "type": "text"}], [{"text": "  64", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "672"}]]}'::jsonb
  WHEN 63 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   22", "type": "text"}], [{"text": "  22", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "242"}]]}'::jsonb
  WHEN 64 THEN '{"type": "multiplication", "lines": [[{"text": "   41", "type": "text"}], [{"text": "×  14", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "  164", "type": "text"}], [{"text": "  41", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "574"}]]}'::jsonb
  WHEN 65 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  24", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   88", "type": "text"}], [{"text": "  44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "528"}]]}'::jsonb
  WHEN 66 THEN '{"type": "multiplication", "lines": [[{"text": "   13", "type": "text"}], [{"text": "×  31", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   13", "type": "text"}], [{"text": "  39", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "403"}]]}'::jsonb
  WHEN 67 THEN '{"type": "multiplication", "lines": [[{"text": "   13", "type": "text"}], [{"text": "×  33", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   39", "type": "text"}], [{"text": "  39", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "429"}]]}'::jsonb
  WHEN 68 THEN '{"type": "multiplication", "lines": [[{"text": "   42", "type": "text"}], [{"text": "×  22", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   84", "type": "text"}], [{"text": "  84", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "924"}]]}'::jsonb
  WHEN 69 THEN '{"type": "multiplication", "lines": [[{"text": "   21", "type": "text"}], [{"text": "×  33", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   63", "type": "text"}], [{"text": "  63", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "693"}]]}'::jsonb
  WHEN 70 THEN '{"type": "multiplication", "lines": [[{"text": "   41", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   41", "type": "text"}], [{"text": "  41", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "451"}]]}'::jsonb
END WHERE id IN (51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70);