UPDATE calc_question SET raw_content = CASE id
  WHEN 71 THEN '{"type": "multiplication", "lines": [[{"text": "   11", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   11", "type": "text"}], [{"text": "  11", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "121"}]]}'::jsonb
  WHEN 72 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  33", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   66", "type": "text"}], [{"text": "  66", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "726"}]]}'::jsonb
  WHEN 73 THEN '{"type": "multiplication", "lines": [[{"text": "    41", "type": "text"}], [{"text": "×   44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   164", "type": "text"}], [{"text": "  164", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1804"}]]}'::jsonb
  WHEN 74 THEN '{"type": "multiplication", "lines": [[{"text": "    31", "type": "text"}], [{"text": "×   33", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    93", "type": "text"}], [{"text": "   93", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1023"}]]}'::jsonb
  WHEN 75 THEN '{"type": "multiplication", "lines": [[{"text": "   11", "type": "text"}], [{"text": "×  42", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   22", "type": "text"}], [{"text": "  44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "462"}]]}'::jsonb
  WHEN 76 THEN '{"type": "multiplication", "lines": [[{"text": "    33", "type": "text"}], [{"text": "×   32", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "    66", "type": "text"}], [{"text": "   99", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1056"}]]}'::jsonb
  WHEN 77 THEN '{"type": "multiplication", "lines": [[{"text": "   11", "type": "text"}], [{"text": "×  44", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   44", "type": "text"}], [{"text": "  44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "484"}]]}'::jsonb
  WHEN 78 THEN '{"type": "multiplication", "lines": [[{"text": "   11", "type": "text"}], [{"text": "×  13", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   33", "type": "text"}], [{"text": "  11", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "143"}]]}'::jsonb
  WHEN 79 THEN '{"type": "multiplication", "lines": [[{"text": "   24", "type": "text"}], [{"text": "×  24", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   96", "type": "text"}], [{"text": "  48", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "576"}]]}'::jsonb
  WHEN 80 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  42", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   44", "type": "text"}], [{"text": "  88", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "924"}]]}'::jsonb
  WHEN 81 THEN '{"type": "multiplication", "lines": [[{"text": "   33", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   33", "type": "text"}], [{"text": "  33", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "363"}]]}'::jsonb
  WHEN 82 THEN '{"type": "multiplication", "lines": [[{"text": "   12", "type": "text"}], [{"text": "×  22", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   24", "type": "text"}], [{"text": "  24", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "264"}]]}'::jsonb
  WHEN 83 THEN '{"type": "multiplication", "lines": [[{"text": "   21", "type": "text"}], [{"text": "×  12", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   42", "type": "text"}], [{"text": "  21", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "252"}]]}'::jsonb
  WHEN 84 THEN '{"type": "multiplication", "lines": [[{"text": "   22", "type": "text"}], [{"text": "×  22", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   44", "type": "text"}], [{"text": "  44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "484"}]]}'::jsonb
  WHEN 85 THEN '{"type": "multiplication", "lines": [[{"text": "    42", "type": "text"}], [{"text": "×   24", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   168", "type": "text"}], [{"text": "   84", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1008"}]]}'::jsonb
  WHEN 86 THEN '{"type": "multiplication", "lines": [[{"text": "   14", "type": "text"}], [{"text": "×  44", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   56", "type": "text"}], [{"text": "  56", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "616"}]]}'::jsonb
  WHEN 87 THEN '{"type": "multiplication", "lines": [[{"text": "   32", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   32", "type": "text"}], [{"text": "  32", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "352"}]]}'::jsonb
  WHEN 88 THEN '{"type": "multiplication", "lines": [[{"text": "   31", "type": "text"}], [{"text": "×  11", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   31", "type": "text"}], [{"text": "  31", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "341"}]]}'::jsonb
  WHEN 89 THEN '{"type": "multiplication", "lines": [[{"text": "   14", "type": "text"}], [{"text": "×  14", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   56", "type": "text"}], [{"text": "  14", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "196"}]]}'::jsonb
  WHEN 90 THEN '{"type": "multiplication", "lines": [[{"text": "   21", "type": "text"}], [{"text": "×  41", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   21", "type": "text"}], [{"text": "  84", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "861"}]]}'::jsonb
END WHERE id IN (71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90);