UPDATE calc_question SET raw_content = CASE id
  WHEN 151 THEN '{"type": "multiplication", "lines": [[{"text": "    904", "type": "text"}], [{"text": "×    57", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   6328", "type": "text"}], [{"text": "  4520", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "51528"}]]}'::jsonb
  WHEN 152 THEN '{"type": "multiplication", "lines": [[{"text": "    702", "type": "text"}], [{"text": "×    96", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   4212", "type": "text"}], [{"text": "  6318", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "67392"}]]}'::jsonb
  WHEN 153 THEN '{"type": "multiplication", "lines": [[{"text": "    606", "type": "text"}], [{"text": "×    95", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3030", "type": "text"}], [{"text": "  5454", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "57570"}]]}'::jsonb
  WHEN 154 THEN '{"type": "multiplication", "lines": [[{"text": "    205", "type": "text"}], [{"text": "×    75", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1025", "type": "text"}], [{"text": "  1435", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "15375"}]]}'::jsonb
  WHEN 155 THEN '{"type": "multiplication", "lines": [[{"text": "    507", "type": "text"}], [{"text": "×    52", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1014", "type": "text"}], [{"text": "  2535", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "26364"}]]}'::jsonb
  WHEN 156 THEN '{"type": "multiplication", "lines": [[{"text": "    705", "type": "text"}], [{"text": "×    81", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    705", "type": "text"}], [{"text": "  5640", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "57105"}]]}'::jsonb
  WHEN 157 THEN '{"type": "multiplication", "lines": [[{"text": "    304", "type": "text"}], [{"text": "×    64", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1216", "type": "text"}], [{"text": "  1824", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "19456"}]]}'::jsonb
  WHEN 158 THEN '{"type": "multiplication", "lines": [[{"text": "    703", "type": "text"}], [{"text": "×    89", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   6327", "type": "text"}], [{"text": "  5624", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "62567"}]]}'::jsonb
  WHEN 159 THEN '{"type": "multiplication", "lines": [[{"text": "    507", "type": "text"}], [{"text": "×    81", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    507", "type": "text"}], [{"text": "  4056", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "41067"}]]}'::jsonb
  WHEN 160 THEN '{"type": "multiplication", "lines": [[{"text": "   105", "type": "text"}], [{"text": "×   47", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   735", "type": "text"}], [{"text": "  420", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "4935"}]]}'::jsonb
  WHEN 161 THEN '{"type": "multiplication", "lines": [[{"text": "    407", "type": "text"}], [{"text": "×    85", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2035", "type": "text"}], [{"text": "  3256", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "34595"}]]}'::jsonb
  WHEN 162 THEN '{"type": "multiplication", "lines": [[{"text": "    608", "type": "text"}], [{"text": "×    67", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   4256", "type": "text"}], [{"text": "  3648", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "40736"}]]}'::jsonb
  WHEN 163 THEN '{"type": "multiplication", "lines": [[{"text": "    804", "type": "text"}], [{"text": "×    76", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   4824", "type": "text"}], [{"text": "  5628", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "61104"}]]}'::jsonb
  WHEN 164 THEN '{"type": "multiplication", "lines": [[{"text": "    803", "type": "text"}], [{"text": "×    95", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   4015", "type": "text"}], [{"text": "  7227", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "76285"}]]}'::jsonb
  WHEN 165 THEN '{"type": "multiplication", "lines": [[{"text": "    205", "type": "text"}], [{"text": "×    76", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1230", "type": "text"}], [{"text": "  1435", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "15580"}]]}'::jsonb
  WHEN 166 THEN '{"type": "multiplication", "lines": [[{"text": "    602", "type": "text"}], [{"text": "×    41", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    602", "type": "text"}], [{"text": "  2408", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "24682"}]]}'::jsonb
  WHEN 167 THEN '{"type": "multiplication", "lines": [[{"text": "    504", "type": "text"}], [{"text": "×    36", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3024", "type": "text"}], [{"text": "  1512", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "18144"}]]}'::jsonb
  WHEN 168 THEN '{"type": "multiplication", "lines": [[{"text": "   301", "type": "text"}], [{"text": "×   16", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "  1806", "type": "text"}], [{"text": "  301", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "4816"}]]}'::jsonb
  WHEN 169 THEN '{"type": "multiplication", "lines": [[{"text": "    408", "type": "text"}], [{"text": "×    89", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3672", "type": "text"}], [{"text": "  3264", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "36312"}]]}'::jsonb
  WHEN 170 THEN '{"type": "multiplication", "lines": [[{"text": "    208", "type": "text"}], [{"text": "×    64", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    832", "type": "text"}], [{"text": "  1248", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "13312"}]]}'::jsonb
END WHERE id IN (151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170);