UPDATE calc_question SET raw_content = CASE id
  WHEN 211 THEN '{"type": "multiplication", "lines": [[{"text": "    400", "type": "text"}], [{"text": "×    52", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    800", "type": "text"}], [{"text": "  2000", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "20800"}]]}'::jsonb
  WHEN 212 THEN '{"type": "multiplication", "lines": [[{"text": "    300", "type": "text"}], [{"text": "×    59", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2700", "type": "text"}], [{"text": "  1500", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "17700"}]]}'::jsonb
  WHEN 213 THEN '{"type": "multiplication", "lines": [[{"text": "    260", "type": "text"}], [{"text": "×    64", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1040", "type": "text"}], [{"text": "  1560", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "16640"}]]}'::jsonb
  WHEN 214 THEN '{"type": "multiplication", "lines": [[{"text": "   260", "type": "text"}], [{"text": "×   21", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   260", "type": "text"}], [{"text": "  520", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5460"}]]}'::jsonb
  WHEN 215 THEN '{"type": "multiplication", "lines": [[{"text": "   400", "type": "text"}], [{"text": "×   13", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "  1200", "type": "text"}], [{"text": "  400", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5200"}]]}'::jsonb
  WHEN 216 THEN '{"type": "multiplication", "lines": [[{"text": "    600", "type": "text"}], [{"text": "×    80", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  4800", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "48000"}]]}'::jsonb
  WHEN 217 THEN '{"type": "multiplication", "lines": [[{"text": "   120", "type": "text"}], [{"text": "×   55", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   600", "type": "text"}], [{"text": "  600", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "6600"}]]}'::jsonb
  WHEN 218 THEN '{"type": "multiplication", "lines": [[{"text": "    220", "type": "text"}], [{"text": "×    94", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    880", "type": "text"}], [{"text": "  1980", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "20680"}]]}'::jsonb
  WHEN 219 THEN '{"type": "multiplication", "lines": [[{"text": "    150", "type": "text"}], [{"text": "×    94", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    600", "type": "text"}], [{"text": "  1350", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "14100"}]]}'::jsonb
  WHEN 220 THEN '{"type": "multiplication", "lines": [[{"text": "   120", "type": "text"}], [{"text": "×   14", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   480", "type": "text"}], [{"text": "  120", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1680"}]]}'::jsonb
  WHEN 221 THEN '{"type": "multiplication", "lines": [[{"text": "   220", "type": "text"}], [{"text": "×   36", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "  1320", "type": "text"}], [{"text": "  660", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "7920"}]]}'::jsonb
  WHEN 222 THEN '{"type": "multiplication", "lines": [[{"text": "    120", "type": "text"}], [{"text": "×    90", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  1080", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "10800"}]]}'::jsonb
  WHEN 223 THEN '{"type": "multiplication", "lines": [[{"text": "   180", "type": "text"}], [{"text": "×   41", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   180", "type": "text"}], [{"text": "  720", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "7380"}]]}'::jsonb
  WHEN 224 THEN '{"type": "multiplication", "lines": [[{"text": "    180", "type": "text"}], [{"text": "×    71", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    180", "type": "text"}], [{"text": "  1260", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "12780"}]]}'::jsonb
  WHEN 225 THEN '{"type": "multiplication", "lines": [[{"text": "    520", "type": "text"}], [{"text": "×    25", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2600", "type": "text"}], [{"text": "  1040", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "13000"}]]}'::jsonb
  WHEN 226 THEN '{"type": "multiplication", "lines": [[{"text": "    500", "type": "text"}], [{"text": "×    38", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   4000", "type": "text"}], [{"text": "  1500", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "19000"}]]}'::jsonb
  WHEN 227 THEN '{"type": "multiplication", "lines": [[{"text": "    400", "type": "text"}], [{"text": "×    43", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1200", "type": "text"}], [{"text": "  1600", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "17200"}]]}'::jsonb
  WHEN 228 THEN '{"type": "multiplication", "lines": [[{"text": "   300", "type": "text"}], [{"text": "×   32", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   600", "type": "text"}], [{"text": "  900", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "9600"}]]}'::jsonb
  WHEN 229 THEN '{"type": "multiplication", "lines": [[{"text": "    500", "type": "text"}], [{"text": "×    88", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   4000", "type": "text"}], [{"text": "  4000", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "44000"}]]}'::jsonb
  WHEN 230 THEN '{"type": "multiplication", "lines": [[{"text": "    600", "type": "text"}], [{"text": "×    25", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3000", "type": "text"}], [{"text": "  1200", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "15000"}]]}'::jsonb
END WHERE id IN (211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230);