UPDATE calc_question SET raw_content = CASE id
  WHEN 131 THEN '{"type": "multiplication", "lines": [[{"text": "   40", "type": "text"}], [{"text": "×  15", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "  200", "type": "text"}], [{"text": "  40", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "600"}]]}'::jsonb
  WHEN 132 THEN '{"type": "multiplication", "lines": [[{"text": "    96", "type": "text"}], [{"text": "×   36", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   576", "type": "text"}], [{"text": "  288", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3456"}]]}'::jsonb
  WHEN 133 THEN '{"type": "multiplication", "lines": [[{"text": "    63", "type": "text"}], [{"text": "×   54", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   252", "type": "text"}], [{"text": "  315", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3402"}]]}'::jsonb
  WHEN 134 THEN '{"type": "multiplication", "lines": [[{"text": "   47", "type": "text"}], [{"text": "×  20", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "    0", "type": "text"}], [{"text": "  94", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "940"}]]}'::jsonb
  WHEN 135 THEN '{"type": "multiplication", "lines": [[{"text": "    47", "type": "text"}], [{"text": "×   56", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   282", "type": "text"}], [{"text": "  235", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2632"}]]}'::jsonb
  WHEN 136 THEN '{"type": "multiplication", "lines": [[{"text": "    94", "type": "text"}], [{"text": "×   77", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   658", "type": "text"}], [{"text": "  658", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "7238"}]]}'::jsonb
  WHEN 137 THEN '{"type": "multiplication", "lines": [[{"text": "    63", "type": "text"}], [{"text": "×   98", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   504", "type": "text"}], [{"text": "  567", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "6174"}]]}'::jsonb
  WHEN 138 THEN '{"type": "multiplication", "lines": [[{"text": "    80", "type": "text"}], [{"text": "×   54", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   320", "type": "text"}], [{"text": "  400", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "4320"}]]}'::jsonb
  WHEN 139 THEN '{"type": "multiplication", "lines": [[{"text": "   15", "type": "text"}], [{"text": "×  26", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   90", "type": "text"}], [{"text": "  30", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "390"}]]}'::jsonb
  WHEN 140 THEN '{"type": "multiplication", "lines": [[{"text": "    45", "type": "text"}], [{"text": "×   34", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   180", "type": "text"}], [{"text": "  135", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1530"}]]}'::jsonb
  WHEN 141 THEN '{"type": "multiplication", "lines": [[{"text": "    86", "type": "text"}], [{"text": "×   45", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   430", "type": "text"}], [{"text": "  344", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "3870"}]]}'::jsonb
  WHEN 142 THEN '{"type": "multiplication", "lines": [[{"text": "   16", "type": "text"}], [{"text": "×  25", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   80", "type": "text"}], [{"text": "  32", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "400"}]]}'::jsonb
  WHEN 143 THEN '{"type": "multiplication", "lines": [[{"text": "    88", "type": "text"}], [{"text": "×   67", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   616", "type": "text"}], [{"text": "  528", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5896"}]]}'::jsonb
  WHEN 144 THEN '{"type": "multiplication", "lines": [[{"text": "    56", "type": "text"}], [{"text": "×   52", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   112", "type": "text"}], [{"text": "  280", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2912"}]]}'::jsonb
  WHEN 145 THEN '{"type": "multiplication", "lines": [[{"text": "    67", "type": "text"}], [{"text": "×   89", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   603", "type": "text"}], [{"text": "  536", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5963"}]]}'::jsonb
  WHEN 146 THEN '{"type": "multiplication", "lines": [[{"text": "    77", "type": "text"}], [{"text": "×   26", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   462", "type": "text"}], [{"text": "  154", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "2002"}]]}'::jsonb
  WHEN 147 THEN '{"type": "multiplication", "lines": [[{"text": "    61", "type": "text"}], [{"text": "×   85", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   305", "type": "text"}], [{"text": "  488", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5185"}]]}'::jsonb
  WHEN 148 THEN '{"type": "multiplication", "lines": [[{"text": "    36", "type": "text"}], [{"text": "×   44", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   144", "type": "text"}], [{"text": "  144", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1584"}]]}'::jsonb
  WHEN 149 THEN '{"type": "multiplication", "lines": [[{"text": "    17", "type": "text"}], [{"text": "×   67", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   119", "type": "text"}], [{"text": "  102", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "1139"}]]}'::jsonb
  WHEN 150 THEN '{"type": "multiplication", "lines": [[{"text": "   12", "type": "text"}], [{"text": "×  78", "type": "text"}], [{"text": "-----", "type": "text"}], [{"text": "   96", "type": "text"}], [{"text": "  84", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□", "type": "blank", "answer": "936"}]]}'::jsonb
END WHERE id IN (131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150);