UPDATE calc_question SET raw_content = CASE id
  WHEN 231 THEN '{"type": "multiplication", "lines": [[{"text": "   180", "type": "text"}], [{"text": "×   50", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "     0", "type": "text"}], [{"text": "  900", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "9000"}]]}'::jsonb
  WHEN 232 THEN '{"type": "multiplication", "lines": [[{"text": "    150", "type": "text"}], [{"text": "×    85", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    750", "type": "text"}], [{"text": "  1200", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "12750"}]]}'::jsonb
  WHEN 233 THEN '{"type": "multiplication", "lines": [[{"text": "   120", "type": "text"}], [{"text": "×   50", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "     0", "type": "text"}], [{"text": "  600", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "6000"}]]}'::jsonb
  WHEN 234 THEN '{"type": "multiplication", "lines": [[{"text": "    500", "type": "text"}], [{"text": "×    97", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3500", "type": "text"}], [{"text": "  4500", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "48500"}]]}'::jsonb
  WHEN 235 THEN '{"type": "multiplication", "lines": [[{"text": "    350", "type": "text"}], [{"text": "×    61", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    350", "type": "text"}], [{"text": "  2100", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "21350"}]]}'::jsonb
  WHEN 236 THEN '{"type": "multiplication", "lines": [[{"text": "    600", "type": "text"}], [{"text": "×    36", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3600", "type": "text"}], [{"text": "  1800", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "21600"}]]}'::jsonb
  WHEN 237 THEN '{"type": "multiplication", "lines": [[{"text": "    150", "type": "text"}], [{"text": "×    86", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    900", "type": "text"}], [{"text": "  1200", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "12900"}]]}'::jsonb
  WHEN 238 THEN '{"type": "multiplication", "lines": [[{"text": "    600", "type": "text"}], [{"text": "×    91", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    600", "type": "text"}], [{"text": "  5400", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "54600"}]]}'::jsonb
  WHEN 239 THEN '{"type": "multiplication", "lines": [[{"text": "   220", "type": "text"}], [{"text": "×   24", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   880", "type": "text"}], [{"text": "  440", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5280"}]]}'::jsonb
  WHEN 240 THEN '{"type": "multiplication", "lines": [[{"text": "    600", "type": "text"}], [{"text": "×    49", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   5400", "type": "text"}], [{"text": "  2400", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "29400"}]]}'::jsonb
  WHEN 241 THEN '{"type": "multiplication", "lines": [[{"text": "    520", "type": "text"}], [{"text": "×    87", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3640", "type": "text"}], [{"text": "  4160", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "45240"}]]}'::jsonb
  WHEN 242 THEN '{"type": "multiplication", "lines": [[{"text": "    150", "type": "text"}], [{"text": "×    83", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    450", "type": "text"}], [{"text": "  1200", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "12450"}]]}'::jsonb
  WHEN 243 THEN '{"type": "multiplication", "lines": [[{"text": "   120", "type": "text"}], [{"text": "×   55", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   600", "type": "text"}], [{"text": "  600", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "6600"}]]}'::jsonb
  WHEN 244 THEN '{"type": "multiplication", "lines": [[{"text": "    450", "type": "text"}], [{"text": "×    65", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2250", "type": "text"}], [{"text": "  2700", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "29250"}]]}'::jsonb
  WHEN 245 THEN '{"type": "multiplication", "lines": [[{"text": "    520", "type": "text"}], [{"text": "×    58", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   4160", "type": "text"}], [{"text": "  2600", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "30160"}]]}'::jsonb
  WHEN 246 THEN '{"type": "multiplication", "lines": [[{"text": "    150", "type": "text"}], [{"text": "×    75", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    750", "type": "text"}], [{"text": "  1050", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "11250"}]]}'::jsonb
  WHEN 247 THEN '{"type": "multiplication", "lines": [[{"text": "    520", "type": "text"}], [{"text": "×    54", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2080", "type": "text"}], [{"text": "  2600", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "28080"}]]}'::jsonb
  WHEN 248 THEN '{"type": "multiplication", "lines": [[{"text": "   120", "type": "text"}], [{"text": "×   64", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   480", "type": "text"}], [{"text": "  720", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "7680"}]]}'::jsonb
  WHEN 249 THEN '{"type": "multiplication", "lines": [[{"text": "   400", "type": "text"}], [{"text": "×   24", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "  1600", "type": "text"}], [{"text": "  800", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "9600"}]]}'::jsonb
  WHEN 250 THEN '{"type": "multiplication", "lines": [[{"text": "    350", "type": "text"}], [{"text": "×    57", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2450", "type": "text"}], [{"text": "  1750", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "19950"}]]}'::jsonb
END WHERE id IN (231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250);