UPDATE calc_question SET raw_content = CASE id
  WHEN 171 THEN '{"type": "multiplication", "lines": [[{"text": "    407", "type": "text"}], [{"text": "×    74", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1628", "type": "text"}], [{"text": "  2849", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "30118"}]]}'::jsonb
  WHEN 172 THEN '{"type": "multiplication", "lines": [[{"text": "    704", "type": "text"}], [{"text": "×    29", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   6336", "type": "text"}], [{"text": "  1408", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "20416"}]]}'::jsonb
  WHEN 173 THEN '{"type": "multiplication", "lines": [[{"text": "   102", "type": "text"}], [{"text": "×   65", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   510", "type": "text"}], [{"text": "  612", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "6630"}]]}'::jsonb
  WHEN 174 THEN '{"type": "multiplication", "lines": [[{"text": "    403", "type": "text"}], [{"text": "×    77", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2821", "type": "text"}], [{"text": "  2821", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "31031"}]]}'::jsonb
  WHEN 175 THEN '{"type": "multiplication", "lines": [[{"text": "    801", "type": "text"}], [{"text": "×    82", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1602", "type": "text"}], [{"text": "  6408", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "65682"}]]}'::jsonb
  WHEN 176 THEN '{"type": "multiplication", "lines": [[{"text": "    402", "type": "text"}], [{"text": "×    69", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   3618", "type": "text"}], [{"text": "  2412", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "27738"}]]}'::jsonb
  WHEN 177 THEN '{"type": "multiplication", "lines": [[{"text": "    308", "type": "text"}], [{"text": "×    96", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1848", "type": "text"}], [{"text": "  2772", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "29568"}]]}'::jsonb
  WHEN 178 THEN '{"type": "multiplication", "lines": [[{"text": "    909", "type": "text"}], [{"text": "×    87", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   6363", "type": "text"}], [{"text": "  7272", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "79083"}]]}'::jsonb
  WHEN 179 THEN '{"type": "multiplication", "lines": [[{"text": "    608", "type": "text"}], [{"text": "×    89", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   5472", "type": "text"}], [{"text": "  4864", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "54112"}]]}'::jsonb
  WHEN 180 THEN '{"type": "multiplication", "lines": [[{"text": "    907", "type": "text"}], [{"text": "×    81", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    907", "type": "text"}], [{"text": "  7256", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "73467"}]]}'::jsonb
  WHEN 181 THEN '{"type": "multiplication", "lines": [[{"text": "    803", "type": "text"}], [{"text": "×    71", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    803", "type": "text"}], [{"text": "  5621", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "57013"}]]}'::jsonb
  WHEN 182 THEN '{"type": "multiplication", "lines": [[{"text": "    805", "type": "text"}], [{"text": "×    42", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1610", "type": "text"}], [{"text": "  3220", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "33810"}]]}'::jsonb
  WHEN 183 THEN '{"type": "multiplication", "lines": [[{"text": "    509", "type": "text"}], [{"text": "×    73", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   1527", "type": "text"}], [{"text": "  3563", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "37157"}]]}'::jsonb
  WHEN 184 THEN '{"type": "multiplication", "lines": [[{"text": "    405", "type": "text"}], [{"text": "×    67", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2835", "type": "text"}], [{"text": "  2430", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "27135"}]]}'::jsonb
  WHEN 185 THEN '{"type": "multiplication", "lines": [[{"text": "   205", "type": "text"}], [{"text": "×   41", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "   205", "type": "text"}], [{"text": "  820", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "8405"}]]}'::jsonb
  WHEN 186 THEN '{"type": "multiplication", "lines": [[{"text": "    506", "type": "text"}], [{"text": "×    51", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "    506", "type": "text"}], [{"text": "  2530", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "25806"}]]}'::jsonb
  WHEN 187 THEN '{"type": "multiplication", "lines": [[{"text": "    902", "type": "text"}], [{"text": "×    28", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   7216", "type": "text"}], [{"text": "  1804", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "25256"}]]}'::jsonb
  WHEN 188 THEN '{"type": "multiplication", "lines": [[{"text": "    304", "type": "text"}], [{"text": "×    60", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "      0", "type": "text"}], [{"text": "  1824", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "18240"}]]}'::jsonb
  WHEN 189 THEN '{"type": "multiplication", "lines": [[{"text": "   304", "type": "text"}], [{"text": "×   19", "type": "text"}], [{"text": "------", "type": "text"}], [{"text": "  2736", "type": "text"}], [{"text": "  304", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□", "type": "blank", "answer": "5776"}]]}'::jsonb
  WHEN 190 THEN '{"type": "multiplication", "lines": [[{"text": "    707", "type": "text"}], [{"text": "×    53", "type": "text"}], [{"text": "-------", "type": "text"}], [{"text": "   2121", "type": "text"}], [{"text": "  3535", "type": "text"}], [{"text": "--------", "type": "text"}], [{"text": "   ", "type": "text"}, {"text": "□□□□□", "type": "blank", "answer": "37471"}]]}'::jsonb
END WHERE id IN (171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190);